:code.purge(Etop.Agent)
:code.delete(Etop.Agent)

defmodule Etop.Agent do
  @name __MODULE__
  def start do
    if Process.whereis(@name), do: stop()
    {:ok, _acc} = Agent.start(fn -> [] end, name: @name)
  end

  def add(item), do: Agent.cast(@name, &[item | &1])
  def stop, do: Agent.stop(@name)
  def get, do: @name |> Agent.get(& &1) |> Enum.reverse()
end

alias Etop.Agent, as: A
{:ok, acc} = A.start()
## The following items as generated by Etop

A.add(%{
  processes: [
    %{
      fun: ":erl_prim_loader.loop/3",
      memory: 426_508,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 29.28,
      pid: '<0.9.0>',
      reds_diff: 921_464,
      reductions: 921_464,
      state: :waiting
    },
    %{
      fun: "IEx.Evaluator.loop/1",
      memory: 1_115_316,
      msg_q: 0,
      name: "IEx.Evaluator.init/4",
      percent: 27.83,
      pid: '<0.226.0>',
      reds_diff: 875_941,
      reductions: 875_941,
      state: :waiting
    },
    %{
      fun: ":code_server.loop/1",
      memory: 196_980,
      msg_q: 10,
      name: ":erlang.apply/2",
      percent: 7.69,
      pid: '<0.49.0>',
      reds_diff: 241_976,
      reductions: 241_976,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 6.56,
      pid: '<0.64.0>',
      reds_diff: 206_407,
      reductions: 206_407,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 109_396,
      msg_q: 5,
      name: ":user_drv.server/2",
      percent: 5.46,
      pid: '<0.62.0>',
      reds_diff: 172_007,
      reductions: 172_007,
      state: :waiting
    },
    %{
      fun: ":erts_code_purger.wait_for_request/0",
      memory: 20880,
      msg_q: 0,
      name: ":erts_code_purger.start/0",
      percent: 5.22,
      pid: '<0.1.0>',
      reds_diff: 164_253,
      reductions: 164_253,
      state: :waiting
    },
    %{
      fun: ":erts_literal_area_collector.msg_loop/4",
      memory: 2688,
      msg_q: 0,
      name: ":erts_literal_area_collector.start/",
      percent: 5.01,
      pid: '<0.2.0>',
      reds_diff: 157_751,
      reductions: 157_751,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 264_396,
      msg_q: 0,
      name: ":application_controller.start/1",
      percent: 4.89,
      pid: '<0.43.0>',
      reds_diff: 153_876,
      reductions: 153_876,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 4,
      name: ":file_server.init/1",
      percent: 3.59,
      pid: '<0.57.0>',
      reds_diff: 112_924,
      reductions: 112_924,
      state: :waiting
    },
    %{
      fun: ":disk_log.loop/1",
      memory: 264_300,
      msg_q: 0,
      name: ":disk_log.init/2",
      percent: 1.22,
      pid: '<0.79.0>',
      reds_diff: 38389,
      reductions: 38389,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 2.9, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_465,
      binary: 218_688,
      code: 10_318_069,
      ets: 797_536,
      processes: 21_886_368,
      processes_used: 21_885_976,
      system: 19_859_792,
      total: 41_746_160
    },
    node: "nonode@nohost",
    time: "08:36:11"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 30_485_536,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 95.7,
      pid: '<0.449.0>',
      reds_diff: 103_956,
      reductions: 137_331,
      state: :running
    },
    %{
      fun: ":erl_prim_loader.loop/3",
      memory: 426_508,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 3.44,
      pid: '<0.9.0>',
      reds_diff: 3742,
      reductions: 925_206,
      state: :waiting
    },
    %{
      fun: ":code_server.loop/1",
      memory: 196_980,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.55,
      pid: '<0.49.0>',
      reds_diff: 601,
      reductions: 242_577,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.11,
      pid: '<0.57.0>',
      reds_diff: 119,
      reductions: 113_043,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.03,
      pid: '<0.3.0>',
      reds_diff: 30,
      reductions: 23429,
      state: :waiting
    },
    %{
      fun: ":disk_log.loop/1",
      memory: 264_324,
      msg_q: 0,
      name: ":disk_log.init/2",
      percent: 0.0,
      pid: '<0.79.0>',
      reds_diff: 4,
      reductions: 38393,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 495,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 343,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4512,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 170,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 254_120,
      code: 10_350_130,
      ets: 799_808,
      processes: 45_537_024,
      processes_used: 45_535_632,
      system: 19_949_520,
      total: 65_486_544
    },
    node: "nonode@nohost",
    time: "08:36:13"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 33_234_472,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 97.94,
      pid: '<0.449.0>',
      reds_diff: 86335,
      reductions: 223_666,
      state: :running
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.92,
      pid: '<0.64.0>',
      reds_diff: 812,
      reductions: 207_221,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 64284,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.76,
      pid: '<0.62.0>',
      reds_diff: 671,
      reductions: 172_680,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.15,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 113_178,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.03,
      pid: '<0.3.0>',
      reds_diff: 26,
      reductions: 23455,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 497,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 345,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4514,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 172,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 101,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 251_704,
      code: 10_350_130,
      ets: 799_808,
      processes: 48_239_224,
      processes_used: 48_237_832,
      system: 19_947_392,
      total: 68_186_616
    },
    node: "nonode@nohost",
    time: "08:36:15"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 39_903_200,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 98.36,
      pid: '<0.449.0>',
      reds_diff: 46640,
      reductions: 270_306,
      state: :running
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 64284,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.52,
      pid: '<0.62.0>',
      reds_diff: 247,
      reductions: 172_927,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.4,
      pid: '<0.64.0>',
      reds_diff: 189,
      reductions: 207_410,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.28,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 113_313,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.07,
      pid: '<0.3.0>',
      reds_diff: 32,
      reductions: 23487,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 499,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 347,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4516,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 174,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 103,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.0, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 265_248,
      code: 10_350_130,
      ets: 799_808,
      processes: 54_911_576,
      processes_used: 54_910_184,
      system: 19_962_968,
      total: 74_874_544
    },
    node: "nonode@nohost",
    time: "08:36:17"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 34_469_960,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 97.47,
      pid: '<0.449.0>',
      reds_diff: 102_903,
      reductions: 373_209,
      state: :running
    },
    %{
      fun: "IEx.Evaluator.loop/1",
      memory: 1_115_316,
      msg_q: 0,
      name: "IEx.Evaluator.init/4",
      percent: 0.95,
      pid: '<0.226.0>',
      reds_diff: 1007,
      reductions: 876_954,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 5696,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.31,
      pid: '<0.455.0>',
      reds_diff: 322,
      reductions: 322,
      state: :waiting
    },
    %{
      fun: ":io.execute_request/2",
      memory: 2748,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.25,
      pid: '<0.458.0>',
      reds_diff: 268,
      reductions: 268,
      state: :waiting
    },
    %{
      fun: ":gen_event.fetch_msg/6",
      memory: 7060,
      msg_q: 0,
      name: ":gen_event.init_it/6",
      percent: 0.18,
      pid: '<0.218.0>',
      reds_diff: 189,
      reductions: 1279,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.18,
      pid: '<0.62.0>',
      reds_diff: 185,
      reductions: 173_112,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.17,
      pid: '<0.57.0>',
      reds_diff: 184,
      reductions: 113_497,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.14,
      pid: '<0.64.0>',
      reds_diff: 148,
      reductions: 207_558,
      state: :waiting
    },
    %{
      fun: ":disk_log.loop/1",
      memory: 264_324,
      msg_q: 0,
      name: ":disk_log.init/2",
      percent: 0.08,
      pid: '<0.79.0>',
      reds_diff: 80,
      reductions: 38477,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 2688,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.03,
      pid: '<0.456.0>',
      reds_diff: 33,
      reductions: 33,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 4.0, nprocs: "94", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 257_768,
      code: 10_350_130,
      ets: 799_808,
      processes: 49_496_744,
      processes_used: 49_489_992,
      system: 19_957_016,
      total: 69_453_760
    },
    node: "nonode@nohost",
    time: "08:36:19"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 41_141_456,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 90.47,
      pid: '<0.449.0>',
      reds_diff: 46140,
      reductions: 419_349,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 6840,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 7.44,
      pid: '<0.455.0>',
      reds_diff: 3796,
      reductions: 4118,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 1.18,
      pid: '<0.62.0>',
      reds_diff: 604,
      reductions: 173_716,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.35,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 113_678,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 2688,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.16,
      pid: '<0.456.0>',
      reds_diff: 82,
      reductions: 115,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.05,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23541,
      state: :waiting
    },
    %{
      fun: ":disk_log.loop/1",
      memory: 264_348,
      msg_q: 0,
      name: ":disk_log.init/2",
      percent: 0.01,
      pid: '<0.79.0>',
      reds_diff: 4,
      reductions: 38481,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 503,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 351,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4520,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 9.0, nprocs: "94", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 273_208,
      code: 10_350_130,
      ets: 799_808,
      processes: 56_185_544,
      processes_used: 56_181_800,
      system: 19_972_256,
      total: 76_157_800
    },
    node: "nonode@nohost",
    time: "08:36:21"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 47_812_952,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 90.99,
      pid: '<0.449.0>',
      reds_diff: 47107,
      reductions: 466_456,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 10584,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 7.3,
      pid: '<0.455.0>',
      reds_diff: 3777,
      reductions: 7895,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.63,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 174_040,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.35,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 113_859,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 207_650,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 2688,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.17,
      pid: '<0.456.0>',
      reds_diff: 86,
      reductions: 201,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.05,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23569,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 505,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 353,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4522,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 8.0, nprocs: "94", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 290_896,
      code: 10_350_130,
      ets: 799_808,
      processes: 62_880_864,
      processes_used: 62_879_472,
      system: 19_993_720,
      total: 82_874_584
    },
    node: "nonode@nohost",
    time: "08:36:23"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 90_862_440,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 95.72,
      pid: '<0.449.0>',
      reds_diff: 101_815,
      reductions: 568_271,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 16616,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 3.41,
      pid: '<0.455.0>',
      reds_diff: 3631,
      reductions: 11526,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.3,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 174_364,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.17,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 114_040,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.09,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 207_746,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 2688,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.08,
      pid: '<0.456.0>',
      reds_diff: 82,
      reductions: 283,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2908,
      msg_q: 0,
      name: ":ssl_pem_cache.init/1",
      percent: 0.04,
      pid: '<0.127.0>',
      reds_diff: 43,
      reductions: 259,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.03,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23597,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 507,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 355,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 7.9, nprocs: "94", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 269_944,
      code: 10_350_130,
      ets: 799_808,
      processes: 105_908_680,
      processes_used: 105_893_416,
      system: 19_974_096,
      total: 125_882_776
    },
    node: "nonode@nohost",
    time: "08:36:25"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 97_533_936,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 90.94,
      pid: '<0.449.0>',
      reds_diff: 46939,
      reductions: 615_210,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 16616,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 7.33,
      pid: '<0.455.0>',
      reds_diff: 3782,
      reductions: 15308,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.63,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 174_688,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.35,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 114_221,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 207_842,
      state: :waiting
    },
    %{
      fun: "Process.sleep/1",
      memory: 5696,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 0.17,
      pid: '<0.456.0>',
      reds_diff: 89,
      reductions: 372,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.05,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23625,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 509,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 357,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4526,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 7.0, nprocs: "94", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 285_528,
      code: 10_350_130,
      ets: 799_808,
      processes: 112_597_992,
      processes_used: 112_586_920,
      system: 19_989_672,
      total: 132_587_664
    },
    node: "nonode@nohost",
    time: "08:36:27"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 104_205_432,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 91.19,
      pid: '<0.449.0>',
      reds_diff: 46929,
      reductions: 662_139,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 21504,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 7.25,
      pid: '<0.455.0>',
      reds_diff: 3731,
      reductions: 19039,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.63,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 175_012,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.35,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 114_402,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 207_938,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.05,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23653,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 511,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 359,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4528,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 186,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 5.5, nprocs: "93", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 301_040,
      code: 10_350_130,
      ets: 799_808,
      processes: 119_283_232,
      processes_used: 119_278_696,
      system: 20_005_184,
      total: 139_288_416
    },
    node: "nonode@nohost",
    time: "08:36:29"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 110_875_824,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 92.08,
      pid: '<0.449.0>',
      reds_diff: 46838,
      reductions: 708_977,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 29408,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 6.32,
      pid: '<0.455.0>',
      reds_diff: 3217,
      reductions: 22256,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.64,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 175_336,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.36,
      pid: '<0.57.0>',
      reds_diff: 183,
      reductions: 114_585,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 208_034,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 32,
      reductions: 23685,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 513,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 361,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4530,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 188,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "93", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 260_616,
      code: 10_350_130,
      ets: 799_808,
      processes: 125_981_384,
      processes_used: 125_979_168,
      system: 19_967_784,
      total: 145_949_168
    },
    node: "nonode@nohost",
    time: "08:36:31"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 99_115_024,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 96.1,
      pid: '<0.449.0>',
      reds_diff: 98951,
      reductions: 807_928,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 29408,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 3.13,
      pid: '<0.455.0>',
      reds_diff: 3218,
      reductions: 25474,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68004,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.31,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 175_660,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.18,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 114_766,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.09,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 208_130,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.03,
      pid: '<0.3.0>',
      reds_diff: 26,
      reductions: 23711,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 515,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 363,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4532,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 190,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.5, nprocs: "93", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 222_416,
      code: 10_350_130,
      ets: 799_808,
      processes: 114_178_104,
      processes_used: 114_154_848,
      system: 19_930_904,
      total: 134_109_008
    },
    node: "nonode@nohost",
    time: "08:36:33"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 105_785_416,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 91.4,
      pid: '<0.449.0>',
      reds_diff: 46717,
      reductions: 854_645,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 13600,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 7.0,
      pid: '<0.455.0>',
      reds_diff: 3580,
      reductions: 29054,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.66,
      pid: '<0.62.0>',
      reds_diff: 338,
      reductions: 175_998,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.35,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 114_947,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 208_226,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.05,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23739,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 517,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 365,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4534,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 192,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "93", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 237_024,
      code: 10_350_130,
      ets: 799_808,
      processes: 120_848_112,
      processes_used: 120_828_896,
      system: 19_945_512,
      total: 140_793_624
    },
    node: "nonode@nohost",
    time: "08:36:35"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 112_455_808,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 91.95,
      pid: '<0.449.0>',
      reds_diff: 46661,
      reductions: 901_306,
      state: :running
    },
    %{
      fun: "Process.sleep/1",
      memory: 26392,
      msg_q: 0,
      name: ":erlang.apply/2",
      percent: 6.48,
      pid: '<0.455.0>',
      reds_diff: 3288,
      reductions: 32342,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.62,
      pid: '<0.62.0>',
      reds_diff: 317,
      reductions: 176_315,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.36,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 115_128,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.19,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 208_322,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23767,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 519,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 367,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4536,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 194,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.5, nprocs: "93", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 243_568,
      code: 10_350_130,
      ets: 799_808,
      processes: 127_538_960,
      processes_used: 127_527_104,
      system: 19_952_056,
      total: 147_491_016
    },
    node: "nonode@nohost",
    time: "08:36:37"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 119_121_328,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 98.32,
      pid: '<0.449.0>',
      reds_diff: 46854,
      reductions: 948_160,
      state: :running
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.68,
      pid: '<0.62.0>',
      reds_diff: 324,
      reductions: 176_639,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.38,
      pid: '<0.57.0>',
      reds_diff: 181,
      reductions: 115_309,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.2,
      pid: '<0.64.0>',
      reds_diff: 96,
      reductions: 208_418,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23795,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 521,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 369,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4538,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 196,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 125,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 259_040,
      code: 10_350_130,
      ets: 799_808,
      processes: 134_199_616,
      processes_used: 134_194_216,
      system: 19_967_528,
      total: 154_167_144
    },
    node: "nonode@nohost",
    time: "08:36:39"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 125_790_616,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.28,
      pid: '<0.449.0>',
      reds_diff: 46493,
      reductions: 994_653,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.28,
      pid: '<0.57.0>',
      reds_diff: 132,
      reductions: 115_441,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 28,
      reductions: 23823,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 523,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 371,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4540,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 198,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 127,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_641,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 735,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 272_512,
      code: 10_350_130,
      ets: 799_808,
      processes: 140_885_680,
      processes_used: 140_885_680,
      system: 19_983_920,
      total: 160_869_600
    },
    node: "nonode@nohost",
    time: "08:36:41"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 132_459_904,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.24,
      pid: '<0.449.0>',
      reds_diff: 46388,
      reductions: 1_041_041,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.29,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 115_576,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.09,
      pid: '<0.3.0>',
      reds_diff: 44,
      reductions: 23867,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 525,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 373,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4542,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 200,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 129,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_643,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 737,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.0, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 285_968,
      code: 10_350_130,
      ets: 799_808,
      processes: 147_576_928,
      processes_used: 147_576_928,
      system: 20_001_744,
      total: 167_578_672
    },
    node: "nonode@nohost",
    time: "08:36:43"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 97_423_192,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.65,
      pid: '<0.449.0>',
      reds_diff: 95843,
      reductions: 1_136_884,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.14,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 115_711,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.02,
      pid: '<0.3.0>',
      reds_diff: 24,
      reductions: 23891,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 527,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 375,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4544,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 202,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 131,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_645,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 739,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 237_184,
      code: 10_350_130,
      ets: 799_808,
      processes: 112_471_832,
      processes_used: 112_436_800,
      system: 19_953_000,
      total: 132_424_832
    },
    node: "nonode@nohost",
    time: "08:36:45"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 104_092_480,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.27,
      pid: '<0.449.0>',
      reds_diff: 46435,
      reductions: 1_183_319,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.29,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 115_846,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 30,
      reductions: 23921,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 529,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 377,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4546,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 204,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 133,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_647,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 741,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 250_768,
      code: 10_350_130,
      ets: 799_808,
      processes: 119_155_816,
      processes_used: 119_127_384,
      system: 19_966_584,
      total: 139_122_400
    },
    node: "nonode@nohost",
    time: "08:36:47"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 110_761_768,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.27,
      pid: '<0.449.0>',
      reds_diff: 46329,
      reductions: 1_229_648,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.29,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 115_981,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 26,
      reductions: 23947,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 531,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 379,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4548,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 206,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 135,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_649,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 743,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 264_176,
      code: 10_350_130,
      ets: 799_808,
      processes: 125_839_784,
      processes_used: 125_818_632,
      system: 19_979_992,
      total: 145_819_776
    },
    node: "nonode@nohost",
    time: "08:36:49"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 99_115_024,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.69,
      pid: '<0.449.0>',
      reds_diff: 110_067,
      reductions: 1_339_715,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.12,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 116_116,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.03,
      pid: '<0.3.0>',
      reds_diff: 32,
      reductions: 23979,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 533,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 381,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4550,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 208,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 137,
      state: :waiting
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.0,
      pid: '<0.62.0>',
      reds_diff: 2,
      reductions: 176_651,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 745,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 2.0, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 235_584,
      code: 10_350_130,
      ets: 799_808,
      processes: 114_126_488,
      processes_used: 114_124_808,
      system: 19_932_464,
      total: 134_058_952
    },
    node: "nonode@nohost",
    time: "08:36:52"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 105_784_312,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 99.65,
      pid: '<0.449.0>',
      reds_diff: 46606,
      reductions: 1_386_321,
      state: :running
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.29,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 116_251,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.08,
      pid: '<0.64.0>',
      reds_diff: 36,
      reductions: 208_466,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 26,
      reductions: 24005,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 535,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 383,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4552,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 210,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 139,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 7060,
      msg_q: 0,
      name: ":supervisor.ssl_admin_sup/1",
      percent: 0.0,
      pid: '<0.126.0>',
      reds_diff: 2,
      reductions: 747,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 0.5, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 249_104,
      code: 10_350_130,
      ets: 799_808,
      processes: 120_814_008,
      processes_used: 120_812_736,
      system: 19_947_384,
      total: 140_761_392
    },
    node: "nonode@nohost",
    time: "08:36:54"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 112_453_600,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 97.3,
      pid: '<0.449.0>',
      reds_diff: 46630,
      reductions: 1_432_951,
      state: :running
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 1.21,
      pid: '<0.62.0>',
      reds_diff: 578,
      reductions: 177_021,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.78,
      pid: '<0.64.0>',
      reds_diff: 376,
      reductions: 208_842,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.28,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 116_386,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.07,
      pid: '<0.3.0>',
      reds_diff: 32,
      reductions: 24037,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 537,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 385,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4554,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 212,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 141,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.0, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 263_232,
      code: 10_350_130,
      ets: 799_808,
      processes: 127_505_272,
      processes_used: 127_504_000,
      system: 19_965_744,
      total: 147_471_016
    },
    node: "nonode@nohost",
    time: "08:36:56"
  }
})

A.add(%{
  processes: [
    %{
      fun: "Process.info/1",
      memory: 119_122_888,
      msg_q: 0,
      name: "Etop.init/1",
      percent: 98.14,
      pid: '<0.449.0>',
      reds_diff: 46582,
      reductions: 1_479_533,
      state: :running
    },
    %{
      fun: ":user_drv.server_loop/6",
      memory: 68516,
      msg_q: 0,
      name: ":user_drv.server/2",
      percent: 0.77,
      pid: '<0.62.0>',
      reds_diff: 364,
      reductions: 177_385,
      state: :waiting
    },
    %{
      fun: ":group.more_data/6",
      memory: 8_011_832,
      msg_q: 0,
      name: ":group.server/3",
      percent: 0.38,
      pid: '<0.64.0>',
      reds_diff: 182,
      reductions: 209_024,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 426_596,
      msg_q: 0,
      name: ":file_server.init/1",
      percent: 0.28,
      pid: '<0.57.0>',
      reds_diff: 135,
      reductions: 116_521,
      state: :waiting
    },
    %{
      fun: ":erts_dirty_process_signal_handler.msg_loop/0",
      memory: 2688,
      msg_q: 0,
      name: ":erts_dirty_process_signal_handler.",
      percent: 0.06,
      pid: '<0.3.0>',
      reds_diff: 30,
      reductions: 24067,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 6928,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.46.0>',
      reds_diff: 2,
      reductions: 539,
      state: :waiting
    },
    %{
      fun: ":application_master.loop_it/4",
      memory: 2776,
      msg_q: 0,
      name: ":application_master.start_it/4",
      percent: 0.0,
      pid: '<0.91.0>',
      reds_diff: 2,
      reductions: 387,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 55132,
      msg_q: 0,
      name: "Mix.ProjectStack.-start_link/1-fun-",
      percent: 0.0,
      pid: '<0.115.0>',
      reds_diff: 2,
      reductions: 4556,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2820,
      msg_q: 0,
      name: ":rpc.init/1",
      percent: 0.0,
      pid: '<0.51.0>',
      reds_diff: 2,
      reductions: 214,
      state: :waiting
    },
    %{
      fun: ":gen_server.loop/7",
      memory: 2864,
      msg_q: 0,
      name: "Logger.Watcher.init/1",
      percent: 0.0,
      pid: '<0.219.0>',
      reds_diff: 2,
      reductions: 143,
      state: :waiting
    }
  ],
  summary: %{
    load: %{cpu: 1.0, nprocs: "92", runq: 0},
    memory: %{
      atom: 512_625,
      atom_used: 501_973,
      binary: 276_904,
      code: 10_350_130,
      ets: 799_808,
      processes: 134_195_248,
      processes_used: 134_195_248,
      system: 19_983_880,
      total: 154_179_128
    },
    node: "nonode@nohost",
    time: "08:36:58"
  }
})
